# Generated by Django 6.0.2 on 2026-07-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_move_wedding_to_occasions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('story_kicker', models.CharField(blank=True, max_length=120, verbose_name='عنوان کوتاه بخش فلسفه')),
                ('story_title', models.CharField(blank=True, max_length=220, verbose_name='عنوان بخش فلسفه')),
                ('story_text', models.TextField(blank=True, verbose_name='متن بخش فلسفه')),
                ('cta_title', models.CharField(blank=True, max_length=220, verbose_name='عنوان بخش درخواست')),
                ('cta_text', models.TextField(blank=True, verbose_name='متن بخش درخواست')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'متن صفحه ورکشاپ',
                'verbose_name_plural': 'متن صفحه ورکشاپ',
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_occasion',
            field=models.BooleanField(db_index=True, default=False, verbose_name='در کارت\u200cهای مناسبتی نمایش داده شود؟'),
        ),
    ]
