# Generated by Django 6.0.2 on 2026-07-12 16:44

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pagecontentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.category_cover_upload_to, verbose_name='تصویر زیر\u200cدسته'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.event_cover_upload_to, verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='image',
            field=models.ImageField(upload_to=main.models.home_hero_upload_to, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='homeheroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.home_hero_mobile_upload_to, verbose_name='تصویر موبایل'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.news_cover_upload_to, verbose_name='تصویر کاور'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.product_cover_upload_to, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=main.models.product_gallery_upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='sitehero',
            name='image',
            field=models.ImageField(upload_to=main.models.site_hero_upload_to, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='sitehero',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.site_hero_mobile_upload_to, verbose_name='تصویر موبایل'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='برای کارت\u200cهای مناسبتی مثل تولد، تسلیت، عاشقانه و ...', null=True, upload_to=main.models.tag_cover_upload_to, verbose_name='تصویر کارت مناسبتی'),
        ),
    ]
