# Generated by Django 6.0.2 on 2026-08-03 14:42

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_normalize_global_hero_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('image', models.ImageField(upload_to=main.models.wedding_gallery_upload_to, verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=180, verbose_name='متن جایگزین')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'تصویر گالری عروسی',
                'verbose_name_plural': 'گالری عروسی',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeddingMigrationSnapshot',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wedding_migration_snapshot', serialize=False, to='main.product')),
                ('original_category_id', models.PositiveBigIntegerField()),
                ('original_tag_ids', models.JSONField(default=list)),
                ('original_catalog_scope', models.CharField(default='general', max_length=16)),
                ('original_wedding_type', models.CharField(blank=True, default='', max_length=32)),
                ('original_wedding_needs_review', models.BooleanField(default=False)),
                ('original_wedding_sort_order', models.PositiveIntegerField(default=0)),
                ('migration_reason', models.CharField(max_length=80)),
                ('migrated_to_wedding', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تصویر وضعیت مهاجرت عروسی',
                'verbose_name_plural': 'تصاویر وضعیت مهاجرت عروسی',
            },
        ),
        migrations.CreateModel(
            name='WeddingTaxonomyMigrationSnapshot',
            fields=[
                ('key', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('object_kind', models.CharField(max_length=16)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('existed_before', models.BooleanField(default=True)),
                ('original_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تصویر وضعیت رده‌بندی مهاجرت عروسی',
                'verbose_name_plural': 'تصاویر وضعیت رده‌بندی مهاجرت عروسی',
            },
        ),
        migrations.CreateModel(
            name='WeddingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=main.models.wedding_hero_upload_to, verbose_name='Hero دسکتاپ')),
                ('hero_mobile_image', models.ImageField(blank=True, null=True, upload_to=main.models.wedding_hero_mobile_upload_to, verbose_name='Hero موبایل')),
                ('hero_title', models.CharField(default='از بله تا روز عروسی، کنار شما', max_length=220, verbose_name='عنوان Hero')),
                ('hero_text', models.TextField(default='انتخاب گل و شیرینی برای خواستگاری، بله\u200cبرون و روز عروسی با هماهنگی اختصاصی زاد.', verbose_name='متن Hero')),
                ('proposal_title', models.CharField(default='خواستگاری و بله\u200cبرون', max_length=220, verbose_name='عنوان بخش خواستگاری و بله\u200cبرون')),
                ('proposal_text', models.TextField(default='برای شروعی صمیمی و به\u200cیادماندنی، دسته\u200cگل و شیرینی را هماهنگ و یک\u200cجا انتخاب کنید.', verbose_name='توضیح بخش خواستگاری و بله\u200cبرون')),
                ('transition_title', models.CharField(default='از یک بله شیرین تا روزی که همیشه می\u200cماند', max_length=220, verbose_name='عنوان گذار روایی')),
                ('transition_text', models.TextField(default='پس از انتخاب\u200cهای آغاز این مسیر، برای جزئیات روز عروسی هم با همان دقت کنار شما هستیم.', verbose_name='متن گذار روایی')),
                ('wedding_day_title', models.CharField(default='روز عروسی', max_length=220, verbose_name='عنوان بخش روز عروسی')),
                ('wedding_day_text', models.TextField(default='دسته\u200cگل عروس و گل\u200cآرایی ماشین عروس با هماهنگی رنگ، سبک و زمان تحویل.', verbose_name='توضیح بخش روز عروسی')),
                ('gallery_title', models.CharField(default='روایت\u200cهای عروسی زاد', max_length=180, verbose_name='عنوان گالری')),
                ('steps_title', models.CharField(default='مسیر انتخاب و ثبت سفارش', max_length=180, verbose_name='عنوان مراحل سفارش')),
                ('steps_text', models.TextField(default='انتخاب نوع محصول و ثبت گزینه\u200cهای مورد علاقه\nهماهنگی رنگ، بودجه و زمان تحویل با تیم زاد\nتأیید نهایی جزئیات و ثبت سفارش', help_text='هر مرحله را در یک خط جداگانه وارد کنید.', verbose_name='متن مراحل سفارش')),
                ('cta_title', models.CharField(default='برای هماهنگی اختصاصی با زاد در تماس باشید', max_length=220, verbose_name='عنوان CTA نهایی')),
                ('cta_text', models.TextField(default='برای بررسی موجودی، زمان آماده\u200cسازی و جزئیات انتخاب\u200cها ابتدا تماس بگیرید یا در تلگرام پیام بدهید.', verbose_name='متن CTA نهایی')),
                ('contact_url', models.CharField(blank=True, help_text='اختیاری؛ مسیر داخلی، لینک tel: یا آدرس کامل. در حالت خالی شماره تماس سایت استفاده می\u200cشود.', max_length=300, verbose_name='لینک تماس')),
                ('telegram_url', models.URLField(blank=True, help_text='در حالت خالی لینک تلگرام اصلی سایت استفاده می\u200cشود.', max_length=300, verbose_name='لینک Telegram')),
                ('seo_title', models.CharField(blank=True, max_length=180, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='Meta Description')),
                ('open_graph_image', models.ImageField(blank=True, null=True, upload_to=main.models.wedding_open_graph_upload_to, verbose_name='تصویر Open Graph')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه عروسی',
                'verbose_name_plural': 'تنظیمات صفحه عروسی',
            },
        ),
        migrations.CreateModel(
            name='WeddingProduct',
            fields=[
            ],
            options={
                'verbose_name': 'محصول عروسی',
                'verbose_name_plural': 'عروسی',
                'ordering': ['wedding_sort_order', '-updated_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical_category_slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', editable=False, max_length=120, verbose_name='دسته ثابت نشانی محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical_section',
            field=models.CharField(blank=True, choices=[('flowers', 'گل\u200cها'), ('bakery', 'بیکری'), ('gifts', 'هدایا'), ('events', 'رویدادها')], default='', editable=False, max_length=20, verbose_name='بخش ثابت نشانی محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_scope',
            field=models.CharField(choices=[('general', 'کاتالوگ عمومی'), ('wedding', 'عروسی')], db_index=True, default='general', editable=False, max_length=16, verbose_name='محدوده کاتالوگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='wedding_needs_review',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='نیازمند تعیین نوع عروسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='wedding_sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش در عروسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='wedding_type',
            field=models.CharField(blank=True, choices=[('bridal_bouquet', 'دسته\u200cگل عروس'), ('wedding_car', 'ماشین عروس'), ('proposal_bouquet', 'دسته\u200cگل خواستگاری و بله\u200cبرون'), ('proposal_sweets', 'شیرینی خواستگاری و بله\u200cبرون')], db_index=True, default='', max_length=32, verbose_name='نوع محصول عروسی'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['catalog_scope', 'wedding_type', 'wedding_sort_order'], name='product_wedding_listing_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('catalog_scope', 'general'), ('wedding_needs_review', False), ('wedding_type', '')), models.Q(('catalog_scope', 'wedding'), ('wedding_needs_review', True), ('wedding_type', '')), models.Q(('catalog_scope', 'wedding'), ('wedding_needs_review', False), ('wedding_type__in', ('bridal_bouquet', 'wedding_car', 'proposal_bouquet', 'proposal_sweets'))), _connector='OR'), name='product_wedding_scope_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='weddingpagecontent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='single_active_wedding_page_content'),
        ),
        migrations.AddField(
            model_name='weddinggalleryimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.weddingpagecontent', verbose_name='صفحه عروسی'),
        ),
        migrations.AddIndex(
            model_name='weddinggalleryimage',
            index=models.Index(fields=['page', 'sort_order'], name='main_weddin_page_id_266239_idx'),
        ),
    ]
