# Generated by Django 6.0.2 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_wedding_collection_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramBotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text=(
                            "نامی که تیم در پنل مدیریت می‌شناسد."
                        ),
                        max_length=120,
                        verbose_name="نام کاربر",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.PositiveBigIntegerField(
                        help_text=(
                            "User ID عددی تلگرام؛ برای چت خصوصی با Chat ID "
                            "یکسان است."
                        ),
                        unique=True,
                        verbose_name="شناسه عددی تلگرام",
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        help_text="اختیاری؛ با یا بدون @ قابل ثبت است.",
                        max_length=64,
                        verbose_name="نام کاربری تلگرام",
                    ),
                ),
                (
                    "can_receive_leads",
                    models.BooleanField(
                        default=False,
                        verbose_name="پیام فرم‌های سایت را دریافت کند؟",
                    ),
                ),
                (
                    "can_lookup_products",
                    models.BooleanField(
                        default=False,
                        verbose_name="تصویر و قیمت محصول را دریافت کند؟",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        verbose_name="فعال باشد؟",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت داخلی")),
            ],
            options={
                "verbose_name": "کاربر ربات تلگرام",
                "verbose_name_plural": "کاربران ربات تلگرام",
                "ordering": ["name", "telegram_user_id"],
            },
        ),
    ]
