# Generated by Django 6.0.2 on 2026-09-02 15:37

import django.db.models.deletion
import main.models
from django.core.validators import FileExtensionValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_delete_selected_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(help_text='عنوان کوتاهی که زیر حلقه استوری نمایش داده می\u200cشود.', max_length=80, verbose_name='عنوان استوری')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('cover_image', models.ImageField(blank=True, help_text='اختیاری است؛ اگر خالی بماند، پوستر اولین ویدئوی آماده استفاده می\u200cشود.', null=True, upload_to=main.models.story_cover_upload_to, verbose_name='کاور اختصاصی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال باشد؟')),
                ('starts_at', models.DateTimeField(blank=True, help_text='اختیاری؛ اگر خالی باشد، نمایش از همین حالا مجاز است.', null=True, verbose_name='شروع نمایش')),
                ('ends_at', models.DateTimeField(blank=True, help_text='اختیاری؛ بعد از این زمان استوری خودکار از سایت برداشته می\u200cشود.', null=True, verbose_name='پایان نمایش')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'استوری',
                'verbose_name_plural': 'استوری\u200cها',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='story_visible_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='story_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='StoryClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان داخل استوری')),
                ('caption', models.CharField(blank=True, max_length=240, verbose_name='توضیح کوتاه')),
                ('source_video', models.FileField(blank=True, help_text='فایل اصلی فقط برای بهینه\u200cسازی استفاده می\u200cشود و در سایت پخش نمی\u200cشود.', upload_to=main.models.story_clip_source_upload_to, validators=[FileExtensionValidator(allowed_extensions=('mp4', 'mov', 'm4v', 'webm'))], verbose_name='ویدئوی اصلی')),
                ('optimized_video', models.FileField(blank=True, editable=False, upload_to=main.models.story_clip_video_upload_to, verbose_name='ویدئوی بهینه\u200cشده')),
                ('poster_image', models.ImageField(blank=True, editable=False, upload_to=main.models.story_clip_poster_upload_to, verbose_name='پوستر خودکار')),
                ('cta_text', models.CharField(blank=True, help_text='مثلاً «مشاهده محصول». اگر خالی باشد دکمه نشان داده نمی\u200cشود.', max_length=50, verbose_name='متن دکمه')),
                ('cta_url', models.CharField(blank=True, help_text='مسیر داخلی مثل /flowers/ یا یک لینک کامل https:// وارد کنید.', max_length=500, verbose_name='لینک دکمه')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال باشد؟')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب کلیپ')),
                ('processing_status', models.CharField(choices=[('queued', 'در صف بهینه\u200cسازی'), ('processing', 'در حال بهینه\u200cسازی'), ('ready', 'آماده انتشار'), ('failed', 'خطا در پردازش')], db_index=True, default='queued', editable=False, max_length=16, verbose_name='وضعیت پردازش')),
                ('processing_error', models.TextField(blank=True, editable=False, verbose_name='خطای پردازش')),
                ('processing_attempts', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='تعداد تلاش پردازش')),
                ('duration_ms', models.PositiveIntegerField(default=0, editable=False, verbose_name='مدت ویدئو (میلی\u200cثانیه)')),
                ('video_width', models.PositiveIntegerField(default=0, editable=False, verbose_name='عرض خروجی')),
                ('video_height', models.PositiveIntegerField(default=0, editable=False, verbose_name='ارتفاع خروجی')),
                ('optimized_size_bytes', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='حجم خروجی')),
                ('processed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان پایان پردازش')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='main.story', verbose_name='استوری')),
            ],
            options={
                'verbose_name': 'کلیپ استوری',
                'verbose_name_plural': 'کلیپ\u200cهای استوری',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['processing_status', 'created_at'], name='storyclip_queue_idx'), models.Index(fields=['story', 'is_active', 'sort_order'], name='storyclip_public_idx')],
            },
        ),
    ]
