# Generated by Django 6.0.2 on 2026-09-05

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_story_storyclip"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyclip",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="عکس هنگام ذخیره به WebP بهینه تبدیل می‌شود.",
                upload_to=main.models.story_clip_image_upload_to,
                verbose_name="عکس استوری",
            ),
        ),
        migrations.AddField(
            model_name="storyclip",
            name="image_duration_ms",
            field=models.PositiveIntegerField(
                default=5000,
                help_text=(
                    "بین ۲۰۰۰ تا ۱۵۰۰۰ میلی‌ثانیه؛ مقدار پیشنهادی ۵۰۰۰ است."
                ),
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(15000),
                ],
                verbose_name="مدت نمایش عکس (میلی‌ثانیه)",
            ),
        ),
        migrations.AddField(
            model_name="storyclip",
            name="media_type",
            field=models.CharField(
                choices=[("video", "ویدئو"), ("image", "عکس")],
                default="video",
                max_length=10,
                verbose_name="نوع محتوا",
            ),
        ),
        migrations.AlterField(
            model_name="storyclip",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
        ),
        migrations.AlterField(
            model_name="story",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text=(
                    "اختیاری است؛ اگر خالی بماند، تصویر اولین محتوای آماده استفاده می‌شود."
                ),
                null=True,
                upload_to=main.models.story_cover_upload_to,
                verbose_name="کاور اختصاصی",
            ),
        ),
        migrations.AlterModelOptions(
            name="storyclip",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "محتوای استوری",
                "verbose_name_plural": "محتواهای استوری",
            },
        ),
    ]
