# Generated by Django 6.0.2 on 2026-09-09 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_storyclip_image_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingFilm',
            fields=[
            ],
            options={
                'verbose_name': 'فیلم عروسی',
                'verbose_name_plural': 'فیلم\u200cهای عروسی',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.storyclip',),
        ),
        migrations.AlterField(
            model_name='storyclip',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='main.story', verbose_name='استوری'),
        ),
        migrations.AddField(
            model_name='weddingpagecontent',
            name='film_clip',
            field=models.ForeignKey(blank=True, help_text='با دکمهٔ + فیلم را بارگذاری کنید؛ تا آماده\u200cشدن آن، قاب معرفی نمایش داده می\u200cشود.', limit_choices_to={'media_type': 'video', 'story__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedding_pages', to='main.weddingfilm', verbose_name='فیلم گالری'),
        ),
    ]
