# Generated by Django 6.0.2 on 2026-09-12 09:57

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_wedding_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='author_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='نویسندهٔ واقعی'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیح سئو'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_posts', to='main.category', verbose_name='دستهٔ مرتبط'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='related_articles',
            field=models.ManyToManyField(blank=True, to='main.newspost', verbose_name='مطالب مرتبط'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='reviewed_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ بازبینی'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='بازبین واقعی'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='seo_title',
            field=models.CharField(blank=True, max_length=180, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='takeaway',
            field=models.TextField(blank=True, verbose_name='پاسخ کوتاه ابتدای مقاله'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='topic',
            field=models.CharField(choices=[('selection', 'راهنمای انتخاب'), ('order', 'راهنمای سفارش'), ('care', 'نگهداری گل'), ('design', 'طراحی و رنگ')], db_index=True, default='selection', max_length=20, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=models.TextField(blank=True, verbose_name='متن قدیمی'),
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('heading', 'تیتر بخش'), ('text', 'پاراگراف'), ('image', 'تصویر'), ('table', 'جدول مقایسه'), ('quote', 'نکته'), ('cta', 'دعوت به اقدام'), ('faq', 'پرسش و پاسخ')], default='text', max_length=20, verbose_name='نوع بخش')),
                ('title', models.CharField(blank=True, max_length=240, verbose_name='عنوان / پرسش')),
                ('body', models.TextField(blank=True, verbose_name='متن ساده / پاسخ')),
                ('image', models.ImageField(blank=True, upload_to='news/blocks/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='توصیف تصویر')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='زیرنویس')),
                ('table_data', models.JSONField(blank=True, default=list, help_text='آرایهٔ ردیف\u200cها با تعداد ستون یکسان؛ ردیف اول عنوان ستون\u200cهاست، مانند [["نوع", "ویژگی"], ["باکس", "چیدمان در ظرف"]].', verbose_name='ردیف\u200cهای جدول')),
                ('link_label', models.CharField(blank=True, max_length=180, verbose_name='متن پیوند')),
                ('link_url', models.CharField(blank=True, max_length=500, validators=[main.models.validate_editorial_url], verbose_name='مقصد پیوند')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.newspost')),
            ],
            options={
                'verbose_name': 'بخش مقاله',
                'verbose_name_plural': 'بخش\u200cهای مقاله',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180, verbose_name='عنوان پیوند')),
                ('url', models.CharField(max_length=500, validators=[main.models.validate_editorial_url], verbose_name='مقصد')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='توضیح ارتباط / منبع')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_links', to='main.newspost')),
            ],
            options={
                'verbose_name': 'پیوند مقاله',
                'verbose_name_plural': 'پیوندها و منابع مقاله',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ArticleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300, verbose_name='چرا این محصول مرتبط است؟')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_connections', to='main.newspost')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول مرتبط',
                'verbose_name_plural': 'محصولات منتخب مقاله',
                'ordering': ['sort_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('post', 'product'), name='unique_article_product')],
            },
        ),
    ]
