# Generated by Django 6.0.2 on 2026-09-16 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_editorial_content_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'موجود برای فروش'), ('SOLD', 'فروخته شد')], db_index=True, default='AVAILABLE', max_length=12, verbose_name='وضعیت فروش'),
        ),
        migrations.AddField(
            model_name='telegrambotuser',
            name='can_manage_same_day',
            field=models.BooleanField(default=False, verbose_name='محصول ارسال روز را فروخته\u200cشده اعلام کند؟'),
        ),
        migrations.CreateModel(
            name='TelegramSameDayPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_message_id', models.PositiveBigIntegerField()),
                ('telegram_file_id', models.CharField(blank=True, max_length=512)),
                ('telegram_created_at', models.DateTimeField(blank=True, null=True)),
                ('revision_date', models.PositiveBigIntegerField(default=0)),
                ('revision_update_id', models.BigIntegerField(default=-1)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=40)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telegram_same_day_post', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramDiscussionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_message_id', models.PositiveBigIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.telegramsamedaypost')),
            ],
        ),
        migrations.AddConstraint(
            model_name='telegramsamedaypost',
            constraint=models.UniqueConstraint(fields=('telegram_chat_id', 'telegram_message_id'), name='telegram_same_day_post_identity'),
        ),
        migrations.AddConstraint(
            model_name='telegramdiscussionmessage',
            constraint=models.UniqueConstraint(fields=('telegram_chat_id', 'telegram_message_id'), name='telegram_discussion_identity'),
        ),
    ]
