# Generated by Django 6.0.2 on 2026-09-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_telegram_same_day_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsamedaypost',
            name='source_photo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='telegramsamedaypost',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'موجود برای فروش'), ('SOLD', 'فروخته شد'), ('WITHDRAWN', 'کشیده شد / بازیافت شد')], db_index=True, default='AVAILABLE', max_length=12, verbose_name='وضعیت فروش'),
        ),
    ]
