# Generated by Django 6.0.2 on 2026-09-26 10:58

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_same_day_admin_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsamedaypost',
            name='studio_error',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='Florist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=120, verbose_name='نام فلوریست')),
                ('code', models.SlugField(max_length=24, unique=True, verbose_name='کد کوتاه')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('joined_at', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'فلوریست',
                'verbose_name_plural': 'فلوریست\u200cها',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='studio_florist_code_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='StudioIngestionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_message_id', models.PositiveBigIntegerField()),
                ('reason', models.CharField(max_length=255, verbose_name='دلیل رد')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان رفع')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خطای ثبت استودیو',
                'verbose_name_plural': 'خطاهای ثبت استودیو',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('telegram_chat_id', 'telegram_message_id'), name='studio_issue_identity')],
            },
        ),
        migrations.CreateModel(
            name='StudioProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('factor_code', models.CharField(max_length=40, unique=True, verbose_name='شماره فاکتور')),
                ('product_type', models.CharField(choices=[('box', 'باکس گل'), ('bouquet', 'دسته گل / بوکت'), ('jar', 'جار گل'), ('stand', 'استند گل'), ('basket', 'سبد گل'), ('bridal', 'دسته گل عروس'), ('car', 'ماشین عروس'), ('other', 'سایر')], max_length=16, verbose_name='نوع محصول')),
                ('production_type', models.CharField(choices=[('DAILY', 'روزانه'), ('CUSTOM', 'سفارشی')], db_index=True, max_length=8, verbose_name='نوع تولید')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت به تومان')),
                ('status', models.CharField(choices=[('AVAILABLE', 'موجود'), ('SOLD', 'فروخته شده'), ('WITHDRAWN', 'کشیده شده'), ('CANCELLED', 'لغو شده')], db_index=True, default='AVAILABLE', max_length=12, verbose_name='وضعیت')),
                ('image', models.ImageField(blank=True, upload_to='studio/products/', verbose_name='تصویر سفارشی / دستی')),
                ('source', models.CharField(choices=[('TELEGRAM_DAILY', 'تلگرام روزانه'), ('TELEGRAM_CUSTOM', 'تلگرام سفارشی'), ('DASHBOARD', 'داشبورد'), ('ADMIN', 'ادمین')], max_length=20, verbose_name='منبع')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_message_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('telegram_sender_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_file_id', models.CharField(blank=True, max_length=512)),
                ('revision_date', models.PositiveBigIntegerField(default=0)),
                ('revision_update_id', models.BigIntegerField(default=-1)),
                ('produced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='زمان تولید')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان فروش')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_entries', to=settings.AUTH_USER_MODEL)),
                ('florist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studio_products', to='main.florist')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_record', to='main.product')),
            ],
            options={
                'verbose_name': 'محصول استودیو',
                'verbose_name_plural': 'محصولات استودیو',
                'ordering': ['-produced_at', '-pk'],
                'indexes': [models.Index(fields=['florist', 'produced_at'], name='studio_florist_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('telegram_chat_id', 'telegram_message_id'), name='studio_telegram_identity'), models.UniqueConstraint(django.db.models.functions.text.Lower('factor_code'), name='studio_factor_ci_unique'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='studio_price_positive'), models.CheckConstraint(condition=models.Q(('image__gt', ''), ('product__isnull', False), _connector='OR'), name='studio_image_or_public_product'), models.CheckConstraint(condition=models.Q(models.Q(('production_type', 'CUSTOM'), _negated=True), ('product__isnull', True), _connector='OR'), name='studio_custom_private'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'SOLD'), _negated=True), ('sold_at__isnull', False), _connector='OR'), name='studio_sold_has_time'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'WITHDRAWN'), _negated=True), ('withdrawn_at__isnull', False), _connector='OR'), name='studio_withdrawn_has_time'), models.CheckConstraint(condition=models.Q(models.Q(('telegram_chat_id__isnull', True), ('telegram_message_id__isnull', True)), models.Q(('telegram_chat_id__isnull', False), ('telegram_message_id__isnull', False)), _connector='OR'), name='studio_telegram_identity_pair')],
            },
        ),
    ]
