# Generated by Django 6.0.2 on 2026-09-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_studio_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='florist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='studio/florists/', verbose_name='عکس پروفایل'),
        ),
    ]
