# Generated by Django 6.0.2 on 2026-09-28 10:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_florist_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='florist',
            options={'ordering': ['name'], 'permissions': [('manage_studio_accounts', 'مدیریت حساب\u200cهای تیم استودیو')], 'verbose_name': 'فلوریست', 'verbose_name_plural': 'فلوریست\u200cها'},
        ),
        migrations.AddField(
            model_name='florist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_florist', to=settings.AUTH_USER_MODEL, verbose_name='حساب ورود'),
        ),
        migrations.AddField(
            model_name='studioproduct',
            name='submission_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studioproduct',
            name='source',
            field=models.CharField(choices=[('PORTAL', 'پنل فلوریست'), ('TELEGRAM_DAILY', 'تلگرام روزانه'), ('TELEGRAM_CUSTOM', 'تلگرام سفارشی'), ('DASHBOARD', 'داشبورد'), ('ADMIN', 'ادمین')], max_length=20, verbose_name='منبع'),
        ),
        migrations.CreateModel(
            name='StudioDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('action', models.CharField(choices=[('PUBLISH', 'انتشار در تلگرام'), ('RETIRE', 'خروج از گروه آماده\u200cها')], max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'در صف'), ('SENDING', 'در حال ارسال'), ('RETRY', 'تلاش مجدد زمان\u200cبندی شده'), ('SENT', 'انجام شد'), ('UNCERTAIN', 'نیازمند بررسی پیام در گروه'), ('FAILED', 'نیازمند رسیدگی')], default='PENDING', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('telegram_created_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('manual_retry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_delivery_manual_retries', to=settings.AUTH_USER_MODEL)),
                ('manual_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=64)),
                ('outcome', models.CharField(blank=True, max_length=32)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='main.studioproduct')),
            ],
            options={
                'verbose_name': 'ارسال استودیو',
                'verbose_name_plural': 'صف ارسال استودیو',
                'ordering': ['next_attempt_at', 'pk'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='studio_delivery_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('record', 'action'), name='studio_delivery_record_action_unique')],
            },
        ),
    ]
