# Generated by Django 6.0.2 on 2026-10-04 20:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_studio_admin_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studioproduct',
            name='sales_reopened_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='studiodelivery',
            name='action',
            field=models.CharField(choices=[('SYNC', 'به\u200cروزرسانی پیام محصول'), ('PUBLISH', 'انتشار در تلگرام'), ('RETIRE', 'خروج از گروه آماده\u200cها')], max_length=8),
        ),
        migrations.CreateModel(
            name='StudioSalesAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_audits', to='main.studioproduct')),
            ],
            options={
                'verbose_name': 'سابقهٔ اصلاح فروش',
                'verbose_name_plural': 'سوابق اصلاح فروش',
                'ordering': ['-created_at', '-pk'],
                'permissions': [('use_sales_workspace', 'دسترسی به پنل فروش')],
                'default_permissions': ('view',),
            },
        ),
    ]
