# Generated by Django 6.0.2 on 2026-10-06 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_studioproduct_sales_reopened_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studioproduct',
            name='studio_image_or_public_product',
        ),
        migrations.AlterField(
            model_name='studioproduct',
            name='florist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studio_products', to='main.florist'),
        ),
        migrations.AlterField(
            model_name='studioproduct',
            name='production_type',
            field=models.CharField(choices=[('DAILY', 'روزانه'), ('CUSTOM', 'سفارشی'), ('MISC', 'شاخه و متفرقه')], db_index=True, max_length=8, verbose_name='نوع تولید'),
        ),
        migrations.AddConstraint(
            model_name='studioproduct',
            constraint=models.CheckConstraint(condition=models.Q(('image__gt', ''), ('product__isnull', False), ('production_type', 'MISC'), _connector='OR'), name='studio_image_or_public_product'),
        ),
        migrations.AddConstraint(
            model_name='studioproduct',
            constraint=models.CheckConstraint(condition=models.Q(('production_type', 'MISC'), ('florist__isnull', False), _connector='OR'), name='studio_production_has_florist'),
        ),
        migrations.AddConstraint(
            model_name='studioproduct',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('production_type', 'MISC'), _negated=True), models.Q(('florist__isnull', True), ('product__isnull', True), ('sold_at__isnull', False), ('status__in', ['SOLD', 'DELETED']), ('telegram_chat_id__isnull', True), ('telegram_message_id__isnull', True), models.Q(('notes', ''), _negated=True)), _connector='OR'), name='studio_misc_sale_valid'),
        ),
    ]
