# Generated by Django 6.0.2 on 2026-10-07 15:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_misc_counter_sales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام کالا')),
                ('base_unit', models.CharField(max_length=30, verbose_name='واحد پایه')),
                ('purchase_unit', models.CharField(max_length=30, verbose_name='واحد خرید')),
                ('units_per_purchase', models.DecimalField(decimal_places=3, default=1, max_digits=9, verbose_name='تعداد واحد پایه در واحد خرید')),
                ('default_unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت مرجع واحد خرید (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کالای خرید',
                'verbose_name_plural': 'کالاهای خرید',
                'ordering': ['name', 'pk'],
                'permissions': [('use_procurement_workspace', 'دسترسی به ثبت خرید و دورریز')],
                'default_permissions': ('view',),
                'constraints': [models.CheckConstraint(condition=models.Q(('units_per_purchase__gt', 0)), name='material_conversion_positive'), models.CheckConstraint(condition=models.Q(('default_unit_price__gte', 0)), name='material_price_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('notes', models.CharField(blank=True, max_length=1000, verbose_name='یادداشت')),
                ('submission_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ثبت\u200cشده'), ('VOID', 'باطل\u200cشده')], db_index=True, default='ACTIVE', max_length=8)),
                ('void_reason', models.CharField(blank=True, max_length=500, verbose_name='دلیل ابطال')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=120, verbose_name='فروشنده')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='شماره فاکتور فروشنده')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع فاکتور (تومان)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فاکتور خرید',
                'verbose_name_plural': 'فاکتورهای خرید',
                'ordering': ['-date', '-pk'],
                'abstract': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=120)),
                ('base_unit', models.CharField(max_length=30)),
                ('unit_label', models.CharField(max_length=30)),
                ('unit_mode', models.CharField(choices=[('base', 'واحد پایه'), ('purchase', 'واحد خرید')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('conversion_factor', models.DecimalField(decimal_places=3, max_digits=9)),
                ('base_quantity', models.DecimalField(decimal_places=6, max_digits=21)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت واحد (تومان)')),
                ('total', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='جمع ردیف (تومان)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='main.purchaseinvoice')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='main.material')),
            ],
            options={
                'verbose_name': 'ردیف خرید',
                'verbose_name_plural': 'ردیف\u200cهای خرید',
                'ordering': ['pk'],
                'abstract': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='WasteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('notes', models.CharField(blank=True, max_length=1000, verbose_name='یادداشت')),
                ('submission_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ثبت\u200cشده'), ('VOID', 'باطل\u200cشده')], db_index=True, default='ACTIVE', max_length=8)),
                ('void_reason', models.CharField(blank=True, max_length=500, verbose_name='دلیل ابطال')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('wilted', 'پژمردگی'), ('damaged', 'آسیب\u200cدیدگی'), ('expired', 'گذشت زمان نگهداری'), ('other', 'سایر')], default='wilted', max_length=12, verbose_name='علت دورریز')),
                ('estimated_total', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='ارزش برآوردی دورریز (تومان)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ثبت دورریز',
                'verbose_name_plural': 'ثبت\u200cهای دورریز',
                'ordering': ['-date', '-pk'],
                'abstract': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='WasteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=120)),
                ('base_unit', models.CharField(max_length=30)),
                ('unit_label', models.CharField(max_length=30)),
                ('unit_mode', models.CharField(choices=[('base', 'واحد پایه'), ('purchase', 'واحد خرید')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('conversion_factor', models.DecimalField(decimal_places=3, max_digits=9)),
                ('base_quantity', models.DecimalField(decimal_places=6, max_digits=21)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=24, verbose_name='بهای هر واحد پایه')),
                ('estimated_cost', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='ارزش برآوردی (تومان)')),
                ('cost_source', models.CharField(choices=[('purchase', 'آخرین خرید ثبت\u200cشده تا تاریخ دورریز'), ('reference', 'قیمت مرجع کالا')], max_length=12)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='main.wasteentry')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='main.material')),
                ('purchase_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_cost_snapshots', to='main.purchaseline')),
            ],
            options={
                'verbose_name': 'ردیف دورریز',
                'verbose_name_plural': 'ردیف\u200cهای دورریز',
                'ordering': ['pk'],
                'abstract': False,
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='ProcurementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=150)),
                ('target_type', models.CharField(max_length=20)),
                ('target_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(max_length=20)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سابقهٔ خرید و دورریز',
                'verbose_name_plural': 'سوابق خرید و دورریز',
                'ordering': ['-created_at', '-pk'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='procurement_audit_target')],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='purchase_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), ('void_reason', ''), ('voided_at__isnull', True)), models.Q(('status', 'VOID'), ('voided_at__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='purchase_void_consistent'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchaseline_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_factor__gt', 0)), name='purchaseline_factor_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', 0)), name='purchaseline_base_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_mode', 'purchase'), models.Q(('conversion_factor', 1), ('unit_mode', 'base')), _connector='OR'), name='purchaseline_unit_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0), ('unit_price__gte', 0)), name='purchase_line_price_valid'),
        ),
        migrations.AddConstraint(
            model_name='wasteentry',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_total__gte', 0)), name='waste_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wasteentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), ('void_reason', ''), ('voided_at__isnull', True)), models.Q(('status', 'VOID'), ('voided_at__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='waste_void_consistent'),
        ),
        migrations.AddConstraint(
            model_name='wasteline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='wasteline_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='wasteline',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_factor__gt', 0)), name='wasteline_factor_positive'),
        ),
        migrations.AddConstraint(
            model_name='wasteline',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', 0)), name='wasteline_base_positive'),
        ),
        migrations.AddConstraint(
            model_name='wasteline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_mode', 'purchase'), models.Q(('conversion_factor', 1), ('unit_mode', 'base')), _connector='OR'), name='wasteline_unit_valid'),
        ),
        migrations.AddConstraint(
            model_name='wasteline',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_cost__gte', 0), ('unit_cost__gte', 0)), name='waste_line_price_valid'),
        ),
        migrations.AddConstraint(
            model_name='wasteline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cost_source', 'purchase'), ('purchase_line__isnull', False)), models.Q(('cost_source', 'reference'), ('purchase_line__isnull', True)), _connector='OR'), name='waste_cost_source_valid'),
        ),
    ]
